# Generated by Django 5.2.11 on 2026-02-28 02:41

import characters.fields
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=200)),
                ("race", models.CharField(blank=True, max_length=100, null=True)),
                ("sex", models.CharField(blank=True, max_length=20, null=True)),
                ("char_class", models.CharField(blank=True, max_length=100, null=True)),
                ("level", models.IntegerField(blank=True, null=True)),
                ("xp", models.IntegerField(blank=True, null=True)),
                ("strength", models.IntegerField(blank=True, null=True)),
                ("dexterity", models.IntegerField(blank=True, null=True)),
                ("constitution", models.IntegerField(blank=True, null=True)),
                ("intelligence", models.IntegerField(blank=True, null=True)),
                ("wisdom", models.IntegerField(blank=True, null=True)),
                ("charisma", models.IntegerField(blank=True, null=True)),
                ("height", characters.fields.PintField(blank=True, null=True)),
                ("weight", characters.fields.PintField(blank=True, null=True)),
                ("current_hp", models.IntegerField(blank=True, null=True)),
                ("gp", characters.fields.PintField(default="0 gp")),
                ("sp", characters.fields.PintField(default="0 sp")),
                ("cp", characters.fields.PintField(default="0 cp")),
                (
                    "encumbrance_multiplier",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.0"), max_digits=5
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("background", models.TextField(blank=True, default="")),
                ("appearance", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="characters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_type", models.CharField(max_length=50)),
                ("forward_data", models.JSONField(default=dict)),
                ("reverse_data", models.JSONField(default=dict)),
                ("is_undone", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("group_id", models.CharField(blank=True, max_length=100, null=True)),
                ("sequence", models.IntegerField(default=0)),
                (
                    "character",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="characters.character",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="Condition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modifier_type",
                    models.CharField(
                        choices=[
                            ("ability", "Ability"),
                            ("weight", "Weight"),
                            ("action_point", "Action Point"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target", models.CharField(blank=True, max_length=50, null=True)),
                ("value", models.IntegerField()),
                ("source", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditions",
                        to="characters.character",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HitDie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.IntegerField()),
                ("die_type", models.CharField(max_length=10)),
                ("roll", models.IntegerField()),
                ("con_bonus", models.IntegerField(default=0)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hit_dice",
                        to="characters.character",
                    ),
                ),
            ],
            options={
                "ordering": ["level"],
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("weight", characters.fields.PintField(default="0 oz")),
                ("unit", characters.fields.PintField(default="1 item")),
                ("is_carried", models.BooleanField(default=True)),
                ("is_worn", models.BooleanField(default=False)),
                ("props", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "container",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contents",
                        to="characters.item",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="characters.character",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Spell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("level", models.IntegerField()),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spells",
                        to="characters.character",
                    ),
                ),
            ],
            options={
                "ordering": ["level", "name"],
                "unique_together": {("character", "name")},
            },
        ),
    ]
