# Generated by Django 5.2.11 on 2026-02-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hitdie",
            options={"ordering": ["is_bodymass", "level"]},
        ),
        migrations.AddField(
            model_name="hitdie",
            name="is_bodymass",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="hitdie",
            name="level",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
