# Generated by Django 5.2.11 on 2026-02-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0002_alter_hitdie_options_hitdie_is_bodymass_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="percentile_strength",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
