# Generated by Django 5.2.11 on 2026-02-28 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0003_character_percentile_strength"),
    ]

    operations = [
        migrations.AddField(
            model_name="condition",
            name="scope",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
