# Generated by Django 5.2.11 on 2026-02-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0004_condition_scope"),
    ]

    operations = [
        migrations.AlterField(
            model_name="condition",
            name="scope",
            field=models.CharField(
                blank=True,
                choices=[("encumbrance", "Encumbrance")],
                max_length=50,
                null=True,
            ),
        ),
    ]
