# Generated by Django 5.2.11 on 2026-03-14 17:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0005_alter_condition_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="chosen_field",
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="character",
            name="chosen_study",
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name="SageStudyPoints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("study", models.CharField(max_length=200)),
                (
                    "points",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sage_studies",
                        to="characters.character",
                    ),
                ),
            ],
            options={
                "ordering": ["study"],
                "unique_together": {("character", "study")},
            },
        ),
    ]
