# Generated by Django 5.2.11 on 2026-05-22 02:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0008_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="spell",
            name="is_memorized",
            field=models.BooleanField(default=True),
        ),
    ]
