# Generated by Django 5.2.11 on 2026-05-22 03:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0009_add_spell_is_memorized"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Action",
        ),
    ]
