# Generated by Django 5.2.11 on 2026-06-20 22:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0010_remove_action_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="BonusHitPoints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("note", models.CharField(max_length=200)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bonus_hit_points",
                        to="characters.character",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
    ]
