# Generated by Django 5.2.11 on 2026-07-10 03:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0012_layoutorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="display_name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
    ]
