# Generated by Django 5.2.11 on 2026-07-10 03:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0013_profile_display_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1)), name="item_quantity_gte_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_container", False), ("quantity", 1), _connector="OR"
                ),
                name="item_container_quantity_1",
            ),
        ),
    ]
