# Generated by Django 5.2.11 on 2026-07-10 03:58

from django.db import migrations, models

import characters.fields


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0015_consolidate_duplicate_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gp", "gold pieces"),
                    ("sp", "silver pieces"),
                    ("cp", "copper pieces"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="weight",
            field=characters.fields.PintField(blank=True, default="0 oz", null=True),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("currency__isnull", True),
                    models.Q(("is_container", False), ("weight__isnull", True)),
                    _connector="OR",
                ),
                name="item_money_no_weight_no_container",
            ),
        ),
    ]
