# Generated by Django 5.2.11 on 2026-07-10 03:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0017_coins_to_items"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="cp",
        ),
        migrations.RemoveField(
            model_name="character",
            name="gp",
        ),
        migrations.RemoveField(
            model_name="character",
            name="sp",
        ),
    ]
