# Generated by Django 5.2.11 on 2026-07-10 23:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0018_remove_character_coin_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
