# Generated by Django 5.2.11 on 2026-07-10 23:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0019_character_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sagestudypoints",
            options={"ordering": ["study"], "verbose_name_plural": "Sage study points"},
        ),
    ]
