# Generated by Django 5.2.11 on 2026-07-11 04:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0020_alter_sagestudypoints_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="wiki_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
