# Generated by Django 5.2.11 on 2026-07-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0021_character_wiki_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="sync_from_wiki",
            field=models.BooleanField(default=False),
        ),
    ]
