# Generated by Django 5.2.11 on 2026-07-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0022_character_sync_from_wiki"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="kind",
            field=models.CharField(
                choices=[
                    ("primary", "Primary"),
                    ("hench", "Henchman"),
                    ("follower", "Follower"),
                    ("hireling", "Hireling"),
                    ("pet", "Pet"),
                ],
                default="primary",
                max_length=20,
            ),
        ),
    ]
