# Generated by Django 5.2.11 on 2026-07-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0023_character_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="armor_class",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
