# Generated by Django 5.2.11 on 2026-07-21 01:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0024_character_armor_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="sagestudypoints",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
    ]
