# Generated by Django 5.2.11 on 2026-07-21 02:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0025_sagestudypoints_hidden"),
    ]

    operations = [
        migrations.CreateModel(
            name="SageAbilityPoints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ability", models.CharField(max_length=200)),
                (
                    "points",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("hidden", models.BooleanField(default=False)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sage_abilities",
                        to="characters.character",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Sage ability points",
                "ordering": ["ability"],
                "unique_together": {("character", "ability")},
            },
        ),
    ]
