# Generated by Django 5.2.11 on 2026-07-21 03:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0026_sageabilitypoints"),
    ]

    operations = [
        migrations.AddField(
            model_name="sageabilitypoints",
            name="source",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
