# Generated by Django 5.2.11 on 2026-08-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0027_sageabilitypoints_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="character-pictures/"
            ),
        ),
    ]
