# Generated by Django 5.2.11 on 2026-08-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0029_multiple_chosen_sage_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sagestudypoints",
            options={
                "ordering": ["study", "concentration"],
                "verbose_name_plural": "Sage study points",
            },
        ),
        migrations.AlterUniqueTogether(
            name="sagestudypoints",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="sagestudypoints",
            name="concentration",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="sagestudypoints",
            unique_together={("character", "study", "concentration")},
        ),
    ]
