# Generated by Django 5.2.11 on 2026-08-17 00:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0031_character_sync_warnings"),
    ]

    operations = [
        migrations.AddField(
            model_name="sageabilitypoints",
            name="study",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.CreateModel(
            name="SageConcentration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "points",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("hidden", models.BooleanField(default=False)),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concentrations",
                        to="characters.sagestudypoints",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Sage concentrations",
                "ordering": ["name"],
                "unique_together": {("study", "name")},
            },
        ),
    ]
