# Generated by Django 5.2.11 on 2026-08-17 01:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0032_sageabilitypoints_study_sageconcentration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sageconcentration",
            options={
                "ordering": ["-granted", "name"],
                "verbose_name_plural": "Sage concentrations",
            },
        ),
        migrations.AddField(
            model_name="sageconcentration",
            name="granted",
            field=models.BooleanField(default=False),
        ),
    ]
