# Generated by Django 5.2.11 on 2026-08-18 03:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0033_alter_sageconcentration_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventionMaintenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance",
                        to="characters.item",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance",
                        to="characters.sagestudypoints",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Invention maintenance",
                "unique_together": {("study", "item")},
            },
        ),
    ]
