# Generated by Django 5.2.11 on 2026-09-12 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0035_parcel_building"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="location_building",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stored_items",
                to="characters.building",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="location_parcel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stored_items",
                to="characters.parcel",
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("location_parcel__isnull", True),
                    ("location_building__isnull", True),
                    _connector="OR",
                ),
                name="item_at_most_one_location",
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_carried", False),
                    models.Q(
                        ("location_building__isnull", True),
                        ("location_parcel__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="item_carried_has_no_location",
            ),
        ),
    ]
