# Generated by Django 5.2.11 on 2026-09-12 22:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0037_trade_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildingMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(max_length=60, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "usage",
                    models.CharField(
                        choices=[
                            ("wall", "wall"),
                            ("floor", "floor or ceiling"),
                            ("roof", "roof"),
                            ("solid", "solid volume"),
                            ("opening", "door or window"),
                            ("stair", "stair"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[("cuft", "ft³"), ("sqft", "ft²"), ("each", "each")],
                        max_length=4,
                    ),
                ),
                (
                    "units_per_good",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.000001")
                            )
                        ],
                    ),
                ),
                ("basis", models.TextField(blank=True, default="")),
                (
                    "nominal_thickness",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "nominal_width",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "nominal_height",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "good",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="building_materials",
                        to="characters.tradegood",
                    ),
                ),
            ],
            options={
                "ordering": ["usage", "name"],
            },
        ),
    ]
