# Generated by Django 5.2.11 on 2026-09-12 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0038_building_material"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Design",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DesignDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("schema_version", models.PositiveSmallIntegerField()),
                ("document", models.JSONField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DesignVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(blank=True, default="", max_length=500)),
                ("schema_version", models.PositiveSmallIntegerField()),
                ("document", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("built_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name", "pk"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="item",
            name="item_at_most_one_location",
        ),
        migrations.RemoveConstraint(
            model_name="item",
            name="item_carried_has_no_location",
        ),
        migrations.AddField(
            model_name="design",
            name="building",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="designs",
                to="characters.building",
            ),
        ),
        migrations.AddField(
            model_name="designdraft",
            name="design",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drafts",
                to="characters.design",
            ),
        ),
        migrations.AddField(
            model_name="designdraft",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="design_drafts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="designversion",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="design_versions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="designversion",
            name="building",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="design_versions",
                to="characters.building",
            ),
        ),
        migrations.AddField(
            model_name="designversion",
            name="design",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="versions",
                to="characters.design",
            ),
        ),
        migrations.AddField(
            model_name="designversion",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="children",
                to="characters.designversion",
            ),
        ),
        migrations.AddField(
            model_name="designdraft",
            name="base_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="characters.designversion",
            ),
        ),
        migrations.AddField(
            model_name="design",
            name="head",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="characters.designversion",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="building",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="characters.building",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="location_room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stored_items",
                to="characters.room",
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("location_building__isnull", True),
                        ("location_parcel__isnull", True),
                    ),
                    models.Q(
                        ("location_parcel__isnull", True),
                        ("location_room__isnull", True),
                    ),
                    models.Q(
                        ("location_building__isnull", True),
                        ("location_room__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="item_at_most_one_location",
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_carried", False),
                    models.Q(
                        ("location_building__isnull", True),
                        ("location_parcel__isnull", True),
                        ("location_room__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="item_carried_has_no_location",
            ),
        ),
        migrations.AddConstraint(
            model_name="designdraft",
            constraint=models.UniqueConstraint(
                fields=("design", "user"), name="uniq_design_draft_design_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="design",
            constraint=models.UniqueConstraint(
                fields=("building", "name"), name="uniq_design_building_name"
            ),
        ),
    ]
